@baseUrl = https://fg-api-rest.fly.dev
#@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX2lkIjoxLCJub21icmUiOiJhQGEuY29tIiwiaWF0IjoxNjk3NDY0MTAzfQ.Jx6HocdoKz8H7kxPqrVjmEqYBLmjODjw3CHoWdxjLGs

// Recupera todos los estados de los pedidos   ....ok
GET {{baseUrl}}/pedidos HTTP/1.1 
Authorization: Bearer {{token}}

###
// recupera todos los estados de los pedidos con la opción limit y offset para realizar paginado (en principio por la cantidad de items no hace falta)
GET {{baseUrl}}/pedidos?limit=200 HTTP/1.1 
Authorization: Bearer {{token}}

###
// Recupera el detalle del pedidos id..............ok
GET {{baseUrl}}/pedidos/43/detalle HTTP/1.1 
Authorization: Bearer {{token}}

###
// Recupera todos los estados de los pedidos. 
POST {{baseUrl}}/pedidos HTTP/1.1 
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "cliente_id": 4,
  "fecha": "2023-12-12T13:38:56.000Z",
  "items": [
    {
      "producto_id": 10,
      "unidades": 1001,
      "precio": 500.54
    },
    {
      "producto_id": 10,
      "unidades": 201,
      "precio": 2520.54
    }
  ]
}

###
GET {{baseUrl}}/pedidos?sort=pedido_cab_id:1 HTTP/1.1  
Authorization: Bearer {{token}}


###
// recupera todos los productos que contengan la palabra ELO en el nombre . Ordena por nombre
GET {{baseUrl}}/pedidos?search=ELO HTTP/1.1 
Authorization: Bearer {{token}}

###
// Recupera el detalle del pedidos id..............ok
GET {{baseUrl}}/pedidos?estado_id=10 HTTP/1.1 
Authorization: Bearer {{token}}


