@baseUrl = https://fg-api-rest.fly.dev
#@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvX2lkIjoxLCJub21icmUiOiJhQGEuY29tIiwiaWF0IjoxNjk3NDY0MTAzfQ.Jx6HocdoKz8H7kxPqrVjmEqYBLmjODjw3CHoWdxjLGs

###
// Recupera todos los productos
GET {{baseUrl}}/productos HTTP/1.1 
Authorization: Bearer {{token}}

###
// Recupera todos los productos ordenados por precios de mayor a menor
// los campos posibles para ordenar son: nombre, precio, producto_id
// luego van : -> 1 es para orden ascendente y -1 para descendente
GET {{baseUrl}}/productos?sort=precio:-1 HTTP/1.1  
Authorization: Bearer {{token}}



###
// recupera todos los productos que contengan la palabra ELO en el nombre . Ordena por nombre
GET {{baseUrl}}/productos?search=ELO HTTP/1.1 
Authorization: Bearer {{token}}

###
// recupera todos los productos que contengan la palabra ELO en el nombre
// ordenados por el precio descendente
GET {{baseUrl}}/productos?search=ELO&sort=precio:-1 HTTP/1.1 
Authorization: Bearer {{token}}

###
// recupera todos los productos con limit (cantidad de productos a recuperar) 
// y offset (los que saltea)
// ordenados por el id del producto
GET {{baseUrl}}/productos?offset=5&limit=5&sort=nombre:1 HTTP/1.1 
Authorization: Bearer {{token}}

###
// hecho por mi probando
GET {{baseUrl}}/productos?limit=10 HTTP/1.1 
Authorization: Bearer {{token}}
###
// recuperda los datos de un producto en particular con su :id en el path
GET {{baseUrl}}/productos/110 HTTP/1.1 
Authorization: Bearer {{token}}

###
// para dar de alta un producto, en el boy va el json y devuelve los datos enviados más el id del producto
POST {{baseUrl}}/productos HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Lechuga Mantecosa",
  "precio": 420.00
}


###
// para actualizar nombre y/o precio del producto, va el :id en el path y los campos en el body
PATCH {{baseUrl}}/productos/110 HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Lechuga Mantecosa",
  "precio": 430.00
}

###
//para eliminar un producto, va el :id en el path
DELETE {{baseUrl}}/productos/177 HTTP/1.1
Authorization: Bearer {{token}}